"""Add gender and email column to User model

Revision ID: b5739e5a20e4
Revises: 2c4d38a0dd72
Create Date: 2025-09-02 14:04:42.237272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5739e5a20e4'
down_revision = '2c4d38a0dd72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enum type first
    gender_enum = sa.Enum('Male', 'Female', name='gender_type')
    gender_enum.create(op.get_bind(), checkfirst=True)
    
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('gender', sa.Enum('Male', 'Female', name='gender_type'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('gender')
        batch_op.drop_column('email')
        
    # Drop enum type
    gender_enum = sa.Enum('Male', 'Female', name='gender_type')
    gender_enum.drop(op.get_bind(), checkfirst=True)

    # ### end Alembic commands ###
